### ISSUE TITLE
    why in def forward(self, x) function have "exit(0)"

### ISSUE THREAD

**Issue by HonestyBrave** [Lxrd-AJ/YOLO_V1#2]
hello, Lxrd-AJ:
  I have detail read you blog in "YOLOv1: You Only Look Once"(https://araintelligence.com/blogs/deep-learning/object-detection/yolo_v1/)
 but when i read the yolov1.py, i can't understant why have "exit(0)" in the function of "def forward(self, x)", because i understand that the function "exit(0)" is exit the program,  could give me a more detail explain?

thankyou a lot!
![image](https://user-images.githubusercontent.com/16200506/100517549-2d67e000-31c6-11eb-8c7b-00be864064b9.png)

**Comment by Lxrd-AJ** [comment]
Hi @HonestyBrave , thanks for pointing that out!
I remember debugging and put the `exit(0)` in there. Please disregard it, I'd update the repo with that line removed.
